# Site settings
theme: jekyll-theme-midnight
title: HARRY ZN - Android Developer
SEOTitle: HARRY ZN's Blog | Android Developer
email: harry.zniu100@gmail.com
description: "Keep Passion, Keep Learning, Keep Challenging, Never Be Broken"
keyword: "ZN, Harry, Harry ZN, Android, Google, Android Studio, Training, Study Notes, 牛子瑜, 牛子瑜的博客，Developer, Software Engineer"
url: "https://zniu100.github.io"
baseurl: ""

#Sidebar settings
sidebar: true
sidebar-about-description: "Be a fighter"

# SNS settings

# Analytics settings
# Baidu Analytics
ba_track_id: 9154356e5cda29dc9b07ea2e9542e091

# Google Analytics
ga_track_id: 'UA-106124362-1'            # Format: UA-xxxxxx-xx
ga_domain: auto

